name: send-issue-smartsheet test
run-name: ${{ github.actor }} created an issue
on:
  issues:
    types: [opened] # TODO: Create on: issues: [edited] to connect to Smartsheet PUT request to update issues when edited

env:
  SMART_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  ISSUE_NUM: ${{ github.event.issue.number }}  # Automatically capture the current issue number

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install smartsheet-python-sdk
          pip install python-dotenv

      - name: Fetch Data and Write to Smartsheet
        run: python post-issue-smartsheet.py
        env:
          SMART_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          ISSUE_NUM: ${{ github.event.issue.number }}